// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd1dTzvnEXMe_2YkWRzDqQi7hj91OfQOM',
    appId: '1:472447298728:web:7be191075d76977b16269d',
    messagingSenderId: '472447298728',
    projectId: 'authtutorial-6d4ff',
    authDomain: 'authtutorial-6d4ff.firebaseapp.com',
    storageBucket: 'authtutorial-6d4ff.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqwYaCGlmrTeiL4hOX9_x-WhzjgCpvKyk',
    appId: '1:472447298728:android:f83095167f259e9716269d',
    messagingSenderId: '472447298728',
    projectId: 'authtutorial-6d4ff',
    storageBucket: 'authtutorial-6d4ff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMyCBAwcPW5Eia7MV2sX4WTckIb2Jz-yc',
    appId: '1:472447298728:ios:cefd363e1b30f85e16269d',
    messagingSenderId: '472447298728',
    projectId: 'authtutorial-6d4ff',
    storageBucket: 'authtutorial-6d4ff.firebasestorage.app',
    iosBundleId: 'com.example.authenticationDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMyCBAwcPW5Eia7MV2sX4WTckIb2Jz-yc',
    appId: '1:472447298728:ios:cefd363e1b30f85e16269d',
    messagingSenderId: '472447298728',
    projectId: 'authtutorial-6d4ff',
    storageBucket: 'authtutorial-6d4ff.firebasestorage.app',
    iosBundleId: 'com.example.authenticationDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd1dTzvnEXMe_2YkWRzDqQi7hj91OfQOM',
    appId: '1:472447298728:web:01a673e2f2dcb9d616269d',
    messagingSenderId: '472447298728',
    projectId: 'authtutorial-6d4ff',
    authDomain: 'authtutorial-6d4ff.firebaseapp.com',
    storageBucket: 'authtutorial-6d4ff.firebasestorage.app',
  );
}
